SELECT F.NAME
FROM
(SELECT DISTINCT P.NAME
 FROM TRAINER AS T,CATCHEDPOKEMON AS CP,
 POKEMON AS P
 WHERE T.ID = CP.OWNER_ID
 AND P.ID = CP.PID
 AND T.HOMETOWN = 'Sangnok City') AS F,
 (SELECT DISTINCT P.NAME
 FROM TRAINER AS T,CATCHEDPOKEMON AS CP,
 POKEMON AS P
 WHERE T.ID = CP.OWNER_ID
 AND P.ID = CP.PID
 AND T.HOMETOWN = 'Brown City') AS S
 WHERE F.NAME = S.NAME;