SELECT T.NAME,AVG(CP.LEVEL)
FROM TRAINER AS T,
CATCHEDPOKEMON AS CP,
POKEMON AS P
WHERE T.ID = CP.OWNER_ID
AND CP.PID = P.ID
AND P.TYPE IN ('Normal','Electric')
GROUP BY T.NAME
ORDER BY AVG(CP.LEVEL);