SELECT P1.ID,P1.NAME,P2.NAME,P3.NAME
FROM EVOLUTION AS FIRST,EVOLUTION AS SECOND,
POKEMON AS P1,POKEMON AS P2,POKEMON AS P3
WHERE FIRST.AFTER_ID = SECOND.BEFORE_ID
AND P1.ID = FIRST.BEFORE_ID
AND P2.ID = SECOND.BEFORE_ID
AND P3.ID = SECOND.AFTER_ID
ORDER BY P1.ID;