SELECT P.NAME,CP.LEVEL, CP.NICKNAME
FROM (SELECT * FROM TRAINER AS T
      WHERE T.ID IN (SELECT G.LEADER_ID
                     FROM GYM AS G)
      ) AS T,
      CATCHEDPOKEMON AS CP,
      POKEMON AS P
WHERE T.ID = CP.OWNER_ID
AND CP.PID = P.ID
AND CP.NICKNAME LIKE ('A%')
ORDER BY P.NAME DESC;