SELECT T.NAME
FROM TRAINER AS T,CATCHEDPOKEMON AS CP
WHERE T.ID = CP.OWNER_ID
AND CP.PID IN (SELECT E1.AFTER_ID
      FROM EVOLUTION AS E1 LEFT JOIN
      EVOLUTION AS E2
      ON (E1.AFTER_ID = E2.BEFORE_ID)
WHERE E2.BEFORE_ID IS NULL)
ORDER BY T.NAME;