SELECT T.NAME, SUM(CP.LEVEL)
FROM TRAINER AS T, CATCHEDPOKEMON AS CP
WHERE T.ID = CP.OWNER_ID
GROUP BY T.NAME
HAVING SUM(CP.LEVEL) = (SELECT SUM(CP.LEVEL)
FROM TRAINER AS T, CATCHEDPOKEMON AS CP
WHERE T.ID = CP.OWNER_ID
GROUP BY T.NAME
ORDER BY SUM(CP.LEVEL) DESC LIMIT 1);
