SELECT P.NAME
FROM (SELECT E1.AFTER_ID
      FROM EVOLUTION AS E1 LEFT JOIN
      EVOLUTION AS E2
      ON (E1.AFTER_ID = E2.BEFORE_ID)
WHERE E2.BEFORE_ID IS NULL) AS E JOIN
POKEMON AS P ON (E.AFTER_ID = P.ID)
ORDER BY P.NAME;