SELECT T.HOMETOWN,CP.NICKNAME
FROM TRAINER AS T, CATCHEDPOKEMON AS CP
WHERE T.ID = CP.OWNER_ID
AND (T.HOMETOWN,CP.LEVEL) IN 
(SELECT T.HOMETOWN,MAX(CP.LEVEL)
 FROM CATCHEDPOKEMON AS CP,
 TRAINER AS T
 WHERE T.ID = CP.OWNER_ID
 GROUP BY  T.HOMETOWN)
ORDER BY T.HOMETOWN;